"""empty message

Revision ID: 20815612ed1b
Revises: 
Create Date: 2025-03-11 10:09:16.537346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20815612ed1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'wallets',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('balance', sa.NUMERIC(precision=15, scale=2), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'transactions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('wallet_id', sa.UUID(), nullable=True),
        sa.Column('amount', sa.NUMERIC(precision=15, scale=2), nullable=True),
        sa.Column('transaction_type', sa.Enum('deposit', 'withdraw', name='transaction_types'), nullable=True),
        sa.Column('old_balance', sa.NUMERIC(precision=15, scale=2), nullable=True),
        sa.Column('new_balance', sa.NUMERIC(precision=15, scale=2), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('wallets')
    # ### end Alembic commands ###
